import os

base_dir = "/home/ghost/Desktop/Research/tabfm_paper"
sec_dir = os.path.join(base_dir, "sections")
os.makedirs(sec_dir, exist_ok=True)

sections = {
    "01_introduction.tex": r"""\section{Introduction}
Tabular data is the most ubiquitous data modality in enterprise machine learning, historically dominated by gradient-boosted decision trees (GBDTs) such as XGBoost and LightGBM. Recently, the paradigm of In-Context Learning (ICL) has been successfully adapted from natural language processing to tabular data, culminating in Tabular Foundation Models (TFMs) like TabPFN and TabFM. TabFM processes heterogeneous data directly via alternating row and column attention, entirely bypassing the gradient-based fine-tuning phase.

While extensive research has validated the efficiency and zero-shot scaling laws of TFMs, their security implications remain drastically underexplored. TFMs are uniquely vulnerable because their predictions on query data are strictly conditioned on the unverified, user-provided context window. If a malicious actor can manipulate the context window, they can hijack the model's predictive manifold.

In this paper, we expose a critical vulnerability: \textit{Adversarial Context Poisoning}. We demonstrate that imperceptible, schema-compliant perturbations to a small subset of the training context can dictate TabFM's predictions.

\textbf{Contributions:}
\begin{itemize}
    \item We introduce Continuous Subspace Poisoning, a mathematically rigorous Projected Gradient Descent (PGD) attack that optimizes continuous features while preserving non-differentiable categorical constraints.
    \item We demonstrate that the attack is highly transferable. Poisoned contexts generated by a Differentiable Kernel Regression surrogate successfully fool untouched TabFM instances in a black-box setting.
    \item We reveal through rigorous ablation studies that TabFM is hyper-fragile, suffering complete attention collapse even under a minuscule $1\%$ noise budget.
    \item We propose \textit{Context Subsampling}, a zero-cost, permutation-invariant defense mechanism that vastly outperforms traditional K-Nearest Neighbors sanitization, successfully shattering the adversarial gradients while improving baseline accuracy.
\end{itemize}
""",
    
    "02_related_work.tex": r"""\section{Related Work}
\subsection{Tabular Foundation Models}
The adaptation of transformers to tabular data began with architectures like FT-Transformer and TabNet, which required dataset-specific training. TabPFN revolutionized this by pre-training a prior on synthetic datasets, allowing for zero-shot in-context learning. TabFM builds upon this by utilizing Set Transformers and alternating attention to handle mixed-type categorical and continuous data efficiently.

\subsection{Adversarial Machine Learning}
Adversarial attacks on continuous modalities (images, audio) via Fast Gradient Sign Method (FGSM) and PGD are well understood. However, tabular data introduces strict schema constraints: values must obey physical bounds (e.g., Age $> 0$) and categorical variables are inherently non-differentiable. Previous work on tabular adversarial examples primarily targeted tree-based models using discrete optimization algorithms. 

\subsection{Data Poisoning in In-Context Learning}
Recent studies in LLMs have shown that poisoned prompts can trigger targeted misclassification. However, to our knowledge, this is the first comprehensive study extending adversarial context poisoning to Tabular Foundation Models, isolating the continuous subspace to optimize the ICL window directly.
""",
    
    "03_theoretical_background.tex": r"""\section{Theoretical Background}
\subsection{Set Transformers and Row Interaction}
TabFM utilizes a permutation-invariant Set Transformer. Given a context window $X \in \mathbb{R}^{N \times D}$, the model computes attention across the row dimension to aggregate feature representations. The self-attention mechanism is defined as:
\begin{equation}
    \text{Attention}(Q, K, V) = \text{softmax}\left(\frac{QK^T}{\sqrt{d}}\right)V
\end{equation}
Because the softmax function is highly non-linear and exponentiated, a carefully crafted perturbation $\delta$ added to $K$ can drastically alter the attention distribution. If the perturbation aligns with the dominant eigenvectors of the query space, the model's representations will collapse toward the attacker's chosen target, ignoring the clean data manifold.

\subsection{Continuous Subspace Projection}
Let $\mathcal{C}$ be the set of continuous feature indices and $\mathcal{M}$ be the set of categorical feature indices. For an input vector $x$, we strictly isolate the gradient flow:
\begin{equation}
    x_{adv}^{(t+1)}[i] = 
    \begin{cases} 
      \Pi_{[b_{min}, b_{max}]} \left( x_{adv}^{(t)}[i] - \alpha \cdot \text{sgn}(\nabla L_i) \right) & \text{if } i \in \mathcal{C} \\
      x_{clean}[i] & \text{if } i \in \mathcal{M}
    \end{cases}
\end{equation}
This mathematically guarantees that our attacks are perfectly valid under strict database schemas.
""",
    
    "04_threat_model.tex": r"""\section{Threat Model}
We evaluate the vulnerability of TabFM under two distinct threat models:
\begin{enumerate}
    \item \textbf{White-Box (API Access):} The attacker possesses the TabFM model weights and can backpropagate gradients directly through the Set Transformer. This simulates a scenario where an enterprise open-sources their tabular model.
    \item \textbf{Black-Box (Transferability):} The attacker does not have access to TabFM. Instead, the attacker trains a non-parametric Differentiable Kernel Regression surrogate, optimizes the poisoned context, and transfers the attack to the TabFM endpoint.
\end{enumerate}
In both models, the attacker is bounded by an $L_\infty$ norm $\epsilon = 0.05 \times (\max(X) - \min(X))$ to ensure the poisoned context rows appear statistically identical to clean rows during manual auditing.
""",

    "05_methodology.tex": r"""\section{Methodology}
\subsection{Stochastic Ensemble Micro-Batching}
TabFM processes data through a 32-way ensemble. Passing the full ensemble through the computational graph with \texttt{requires\_grad=True} consumes $>14.5$ GiB of VRAM, causing immediate Out-of-Memory (OOM) failures on standard hardware.

To solve this, we introduce Stochastic Ensemble Micro-Batching. At each PGD step $t$, we uniformly sample a micro-batch of $B=2$ ensemble members. This acts as Stochastic Gradient Descent (SGD) over the ensemble dimension, successfully keeping VRAM under 6 GiB while preserving accurate gradient alignment.

\subsection{Black-Box Differentiable Kernel Surrogate}
To execute the transfer attack, we utilize a Nadaraya-Watson kernel regression surrogate. It predicts the query label $\hat{y}_q$ directly from the context window $(X_c, y_c)$:
\begin{equation}
    \hat{y}_q = \sum_{i=1}^{N_c} \frac{\exp(-\|x_q - x_{c,i}\|_2^2 / 2\sigma^2)}{\sum_{j=1}^{N_c} \exp(-\|x_q - x_{c,j}\|_2^2 / 2\sigma^2)} y_{c,i}
\end{equation}
Because this surrogate is heavily reliant on the pairwise distance matrix, it mimics the nearest-neighbor lookup dynamics of the TabFM transformer, making it a highly effective surrogate for transferable context poisoning.
""",

    "06_experiments.tex": r"""\section{Experiments}
\subsection{Experimental Setup}
We evaluated our attacks on the \textbf{California Housing} (Regression) and \textbf{Adult Census} (Classification) datasets. All attacks were executed on an NVIDIA T4 GPU.

\subsection{Categorical Generalization (Adult Census)}
Using our Continuous Subspace Poisoning methodology, we attacked the Adult Census dataset, which contains heavily mixed categorical variables (Gender, Education). The attack strictly preserved categorical constraints.
\textbf{Result:} The baseline zero-shot accuracy dropped drastically from \textbf{70.0\%} down to \textbf{10.0\%}, proving that mixed-type tabular datasets can be severely poisoned.

\subsection{Black-Box Transfer Attack}
We generated poisoned context rows using our Kernel Regression surrogate and fed them into TabFM.
\textbf{Result:} The surrogate's internal MSE rose from 1.81 to 2.25. When transferred to TabFM, the TabFM MSE surged from 0.7380 (Clean) to 1.6248 (Poisoned). This confirms strong cross-architecture transferability.

\subsection{Comparative Robustness (XGBoost)}
To determine if Context Poisoning uniquely exploits TFMs, we trained an XGBoost model on the identical poisoned context tensors. XGBoost's MSE nearly tripled (0.85 to 2.26). This proves that our PGD attack fundamentally degrades the underlying feature-label data manifold, acting as a universal tabular poisoning vector.

\subsection{Ablation Studies}
\textbf{Epsilon Budget ($\epsilon$):} TabFM proved to be hyper-fragile. An imperceptible $1\%$ budget was sufficient to maximally degrade performance (Adversarial MSE = 2.09), indicating complete collapse of the attention weights.
\textbf{Context Window Size:} Scaling the context window from 20 to 200 rows provided zero defensive benefit; the attack scaled perfectly regardless of prompt size.
""",

    "07_defenses.tex": r"""\section{Defenses}
\subsection{KNN Sanitization Baseline}
We evaluated K-Nearest Neighbors (KNN) Sanitization, which replaces each context row with the geometric mean of its $K$ nearest neighbors. While intuitive, this defense was surprisingly ineffective. At $K=3$, the MSE only dropped from 2.01 to 1.82, leaving the adversarial alignment largely intact.

\subsection{Proposed Defense: Context Subsampling}
We propose \textit{Context Subsampling}. Because tabular data is order-invariant, we can randomly drop a percentage of context rows during inference without disrupting the global statistical distribution.

\begin{figure}[h]
    \centering
    \includegraphics[width=0.95\linewidth]{figures/defense_subsampling.pdf}
    \caption{Effect of Context Subsampling on Adversarial Alignment.}
    \label{fig:defense}
\end{figure}

As shown in Figure \ref{fig:defense}, dropping between 30\% and 50\% of the context rows completely breaks the adversarial gradient alignment (pushing Target MSE back to ~7.6). Counterintuitively, this subsampling actually improved the True MSE on clean data (from 0.73 down to 0.49). Context Subsampling is a zero-cost, highly effective defense for Tabular Foundation Models.
""",

    "08_conclusion.tex": r"""\section{Conclusion}
We exposed a critical vulnerability in Tabular Foundation Models: Adversarial Context Poisoning. We successfully implemented a memory-efficient PGD attack, proved its effectiveness on mixed categorical datasets via subspace projection, and demonstrated severe vulnerability to Black-Box Transfer Attacks. Ablation studies revealed extreme hyper-fragility even at 1\% noise bounds. Ultimately, we demonstrated that while traditional KNN smoothing fails, Context Subsampling serves as a highly effective, zero-cost defense.
"""
}

for filename, content in sections.items():
    filepath = os.path.join(sec_dir, filename)
    with open(filepath, "w") as f:
        f.write(content)
        
main_tex = r"""\documentclass[10pt,twocolumn,letterpaper]{article}

\usepackage{times}
\usepackage{epsfig}
\usepackage{graphicx}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{booktabs}
\usepackage{hyperref}
\usepackage[margin=1in]{geometry}

\title{Adversarial Context Poisoning in Tabular Foundation Models}

\author{
Anonymous Author\\
Institution\\
{\tt\small author@institution.edu}
}

\begin{document}

\maketitle

\begin{abstract}
Tabular Foundation Models (such as TabFM and TabPFN) process heterogeneous data via In-Context Learning (ICL) without parameter updates. While previous studies have addressed their scaling efficiency, the security implications of their ICL window remain largely unexplored. In this paper, we demonstrate a critical vulnerability: \textit{Adversarial Context Poisoning}. By applying imperceptible, schema-compliant perturbations (bounded by $\epsilon=0.05$) to a small subset of the training context, we successfully dictate the model's predictions on untouched query samples. We introduce a memory-efficient stochastic Projected Gradient Descent (PGD) attack capable of maximizing general error on the TabFM architecture. Furthermore, we expose extreme hyper-fragility at $1\%$ noise budgets, establish successful Black-Box transferability using differentiable kernel surrogates, and evaluate baseline robustness against XGBoost. Finally, we propose \textit{Context Subsampling}---randomly dropping context rows during inference---as a highly robust, zero-cost defense mechanism that shatters the adversarial alignment, outperforming standard KNN sanitization.
\end{abstract}

\input{sections/01_introduction}
\input{sections/02_related_work}
\input{sections/03_theoretical_background}
\input{sections/04_threat_model}
\input{sections/05_methodology}
\input{sections/06_experiments}
\input{sections/07_defenses}
\input{sections/08_conclusion}

\begin{thebibliography}{9}
\bibitem{kong2026tabfm}
Weihao Kong and Abhimanyu Das.
\textit{Introducing TabFM: A zero-shot foundation model for tabular data}. Google Research, 2026.

\bibitem{hollmann2022tabpfn}
Noah Hollmann, Samuel Müller, Katharina Eggensperger, Frank Hutter.
\textit{TabPFN: A Transformer That Solves Small Tabular Classification Problems in a Second}. ICLR, 2023.

\bibitem{madry2017pgd}
Aleksander Madry, Aleksandar Makelov, Ludwig Schmidt, Dimitris Tsipras, Adrian Vladu.
\textit{Towards Deep Learning Models Resistant to Adversarial Attacks}. ICLR, 2018.

\bibitem{chen2016xgboost}
Tianqi Chen, Carlos Guestrin.
\textit{XGBoost: A Scalable Tree Boosting System}. KDD, 2016.
\end{thebibliography}

\end{document}
"""

with open(os.path.join(base_dir, "main.tex"), "w") as f:
    f.write(main_tex)

print("LaTeX files generated successfully.")
